import { NPCDefinition, ActionDefinition } from '../../types/game';

export const vandaraNPCs: Record<string, NPCDefinition> = {
  'npc-magistra_solen': {
    id: 'npc-magistra_solen',
    nameKey: 'npc_magistra_solen_name',
    icon: '🔮',
    image: 'img/npcs/magistra_solen.webp',
    progKey: 'magistra_solen',
    maxProgress: 5,
    isVandara: true,
    dialogues: {
      0: 'npc_magistra_solen_1',
    },
  },
  'npc-meister_bram': {
    id: 'npc-meister_bram',
    nameKey: 'npc_meister_bram_name',
    icon: '⚒️',
    image: 'img/npcs/meister_bram.webp',
    progKey: 'meister_bram',
    maxProgress: 5,
    isVandara: true,
    dialogues: {
      0: 'npc_meister_bram_1',
    },
  },
  'npc-lyra': {
    id: 'npc-lyra',
    nameKey: 'npc_lyra_name',
    icon: '🌿',
    image: 'img/npcs/lyra.webp',
    progKey: 'lyra',
    maxProgress: 5,
    isVandara: true,
    dialogues: {
      0: 'npc_lyra_1',
    },
  },
};

export const vandaraActions: Record<string, ActionDefinition> = {
  'act-vandara-magic-runes': {
    id: 'act-vandara-magic-runes',
    category: 'vandara',
    chapter: 'Vandara: Magic Path',
    cost: 15,
    costType: 'magic',
    requirements: { 'academy_path': 'solen' },
    rewards: { study_xp: 5, rune_fragment: 2 },
    sfx: 'magic',
    particleType: 'magic',
  },
  'act-vandara-magic-experiments': {
    id: 'act-vandara-magic-experiments',
    category: 'vandara',
    chapter: 'Vandara: Magic Path',
    cost: 30,
    costType: 'magic',
    requirements: { 'academy_path': 'solen' },
    rewards: { astral_shards: 2, study_xp: 10 },
    sfx: 'magic',
    particleType: 'magic',
  },
  'act-vandara-craft-furniture': {
    id: 'act-vandara-craft-furniture',
    category: 'vandara',
    chapter: 'Vandara: Handwerk Path',
    cost: 20,
    costType: 'energy',
    requirements: { 'academy_path': 'bram' },
    rewards: { study_xp: 5 },
    sfx: 'craft',
  },
  'act-vandara-craft-masterpiece': {
    id: 'act-vandara-craft-masterpiece',
    category: 'vandara',
    chapter: 'Vandara: Handwerk Path',
    cost: 50,
    costType: 'energy',
    requirements: { 'academy_path': 'bram' },
    rewards: { study_xp: 15 },
    sfx: 'success',
  },
  'act-vandara-nature-gather': {
    id: 'act-vandara-nature-gather',
    category: 'vandara',
    chapter: 'Vandara: Natur Path',
    cost: 15,
    costType: 'energy',
    requirements: { 'academy_path': 'lyra' },
    rewards: { study_xp: 5, herbs: 3, flowers: 3 },
    sfx: 'gather',
  },
  'act-vandara-nature-festival': {
    id: 'act-vandara-nature-festival',
    category: 'vandara',
    chapter: 'Vandara: Natur Path',
    cost: 30,
    costType: 'satiation',
    requirements: { 'academy_path': 'lyra' },
    rewards: { study_xp: 15 },
    sfx: 'magic',
  },
};
