import { ItemDefinition } from '../../types/game';

/**
 * Item Database - TypeScript Edition
 * Standardized IDs with 'item-' prefix for robustness.
 */
export const itemDb: Record<string, ItemDefinition> = {
  // --- TOOLS ---
  'item-walking-stick': {
    id: 'item-walking-stick',
    title: 'item_wanderstock_title',
    desc: 'item_wanderstock_desc',
    image: 'img/tools/walkingstick.webp',
    consumable: false,
    category: 'tools',
    modifiers: [
      { key: 'wood_yield', add: 1 },
      { key: 'stone_yield', add: 1 },
    ],
  },
  'item-axe': {
    id: 'item-axe',
    title: 'item_axe_title',
    desc: 'item_axe_desc',
    image: 'img/tools/axe_1.webp',
    consumable: false,
    category: 'tools',
    modifiers: [{ key: 'wood_yield', mult: 2 }],
  },
  'item-pickaxe': {
    id: 'item-pickaxe',
    title: 'item_pickaxe_title',
    desc: 'item_pickaxe_desc',
    image: 'img/tools/pickaxe_1.webp',
    consumable: false,
    category: 'tools',
    modifiers: [{ key: 'stone_yield', mult: 2 }],
  },
  'item-bow': {
    id: 'item-bow',
    title: 'item_bow_title',
    desc: 'item_bow_desc',
    image: 'img/tools/bow.webp',
    consumable: false,
    category: 'tools',
  },
  'item-bed': {
    id: 'item-bed',
    title: 'item_bed_title',
    desc: 'item_bed_desc',
    image: 'img/crafting/bed.webp',
    consumable: false,
    category: 'crafting',
    spaceCost: 2,
    modifiers: [
      { key: 'rest_energy_gain', add: 30 },
      { key: 'energy_limit', add: 50 },
    ],
  },
  'item-chair': {
    id: 'item-chair',
    title: 'item_chair_title',
    desc: 'item_chair_desc',
    image: 'img/crafting/chair.webp',
    consumable: false,
    category: 'crafting',
    spaceCost: 1,
  },
  'item-stove': {
    id: 'item-stove',
    title: 'item_stove_title',
    desc: 'item_stove_desc',
    image: 'img/crafting/stove.webp',
    consumable: false,
    category: 'crafting',
    spaceCost: 2,
    modifiers: [{ key: 'eat_satiation_gain', add: 20 }],
  },
  'item-bookshelf': {
    id: 'item-bookshelf',
    title: 'item_bookshelf_title',
    desc: 'item_bookshelf_desc',
    image: 'img/crafting/bookshelf.webp',
    consumable: false,
    category: 'crafting',
    spaceCost: 1,
    modifiers: [{ key: 'books_limit', add: 5 }],
  },
  'item-cabinet': {
    id: 'item-cabinet',
    title: 'item_cabinet_title',
    desc: 'item_cabinet_desc',
    image: 'img/crafting/cabinet.webp',
    consumable: false,
    category: 'crafting',
    spaceCost: 2,
    modifiers: [
      { key: 'meat_limit', add: 10 },
      { key: 'water_limit', add: 10 },
      { key: 'herbs_limit', add: 20 },
    ],
  },
  'item-spice-rack': {
    id: 'item-spice-rack',
    title: 'item_spice_rack_title',
    desc: 'item_spice_rack_desc',
    image: 'img/tools/spice-rack.webp',
    consumable: false,
    category: 'tools',
    modifiers: [{ key: 'herbs_limit', add: 10 }],
  },
  'item-grand-table': {
    id: 'item-grand-table',
    title: 'item_grand_table_title',
    desc: 'item_grand_table_desc',
    image: 'img/crafting/table_massive.webp',
    consumable: false,
    category: 'crafting',
    spaceCost: 3,
  },

  // --- PROVISIONS ---
  'item-bread': {
    id: 'item-bread',
    title: 'item_bread_title',
    desc: 'item_bread_desc',
    image: 'img/items/bread.webp',
    consumable: true,
    effect: { satiation: 25 },
    category: 'items',
  },
  'item-cookie': {
    id: 'item-cookie',
    title: 'item_cookie_title',
    desc: 'item_cookie_desc',
    image: 'img/items/cookie.webp',
    consumable: true,
    effect: { satiation: 40, energy: 5 },
    category: 'items',
  },
  'item-dried-meat': {
    id: 'item-dried-meat',
    title: 'item_dried_meat_title',
    desc: 'item_dried_meat_desc',
    image: 'img/items/driedmeat.webp',
    consumable: true,
    effect: { satiation: 15, energy: 15 },
    category: 'items',
  },
  'item-gourmet-meal': {
    id: 'item-gourmet-meal',
    title: 'item_gourmet_meal_title',
    desc: 'item_gourmet_meal_desc',
    image: 'img/items/gourmetmeal.webp',
    consumable: true,
    effect: { satiation: 50, energy: 30 },
    category: 'items',
  },

  // --- ARTIFACTS ---
  'item-deed': {
    id: 'item-deed',
    title: 'item_deed_title',
    desc: 'item_deed_desc',
    image: 'img/items/deed.webp',
    consumable: false,
    category: 'items',
  },
  'item-book-knowledge': {
    id: 'item-book-knowledge',
    title: 'item_book_knowledge_title',
    desc: 'item_book_knowledge_desc',
    image: 'img/items/bookknowledge.webp',
    consumable: false,
    category: 'items',
  },
  'item-scroll': {
    id: 'item-scroll',
    title: 'item_scroll_title',
    desc: 'item_scroll_desc',
    image: 'img/items/scroll.webp',
    consumable: false,
    category: 'items',
  },
  'item-whetstone': {
    id: 'item-whetstone',
    title: 'item_whetstone_title',
    desc: 'item_whetstone_desc',
    image: 'img/items/whetstone.webp',
    consumable: false,
    category: 'items',
  },
  'item-arrowhead': {
    id: 'item-arrowhead',
    title: 'item_arrowhead_title',
    desc: 'item_arrowhead_desc',
    image: 'img/items/arrowhead.webp',
    consumable: false,
    category: 'items',
  },
  'item-chisel': {
    id: 'item-chisel',
    title: 'item_chisel_title',
    desc: 'item_chisel_desc',
    image: 'img/tools/chisel.webp',
    consumable: false,
    category: 'tools',
  },
  'item-astral-shards': {
    id: 'item-astral-shards',
    title: 'item_astral_shards_title',
    desc: 'item_astral_shards_desc',
    image: 'img/items/astralshard.webp',
    consumable: false,
    category: 'items',
  },
  'item-dream-dust': {
    id: 'item-dream-dust',
    title: 'item_dream_dust_title',
    desc: 'item_dream_dust_desc',
    image: 'img/items/dreamdust.webp',
    consumable: false,
    category: 'items',
  },
  'item-wyvern-scale': {
    id: 'item-wyvern-scale',
    title: 'item_wyvern_scale_title',
    desc: 'item_wyvern_scale_desc',
    image: 'img/items/wyvernshard.webp',
    consumable: false,
    category: 'items',
  },
  'item-arcane-dust': {
    id: 'item-arcane-dust',
    title: 'item_arcane_dust_title',
    desc: 'item_arcane_dust_desc',
    image: 'img/items/arcane_dust.webp',
    consumable: false,
    category: 'items',
  },
  'item-crystal-mana': {
    id: 'item-crystal-mana',
    title: 'item_crystal_mana_title',
    desc: 'item_crystal_mana_desc',
    image: 'img/items/mana_crystal.webp',
    consumable: false,
    category: 'items',
    modifiers: [{ key: 'garden_magic_cost', mult: 0.8 }],
  },
  'item-bed-2': {
    id: 'item-bed-2',
    title: 'item_bed_2_title',
    desc: 'item_bed_2_desc',
    image: 'img/crafting/bed_2.webp',
    consumable: false,
    category: 'crafting',
    spaceCost: 2,
    modifiers: [
      { key: 'rest_energy_gain', add: 50 },
      { key: 'energy_limit', add: 100 },
    ],
  },
  'item-stove-2': {
    id: 'item-stove-2',
    title: 'item_stove_2_title',
    desc: 'item_stove_2_desc',
    image: 'img/crafting/stove_2.webp',
    consumable: false,
    category: 'crafting',
    spaceCost: 2,
    modifiers: [
      { key: 'eat_satiation_gain', add: 50 },
      { key: 'energy_limit', add: 25 },
    ],
  },
};
