import { ActionDefinition } from '../../types/game';

export const schoolActions: Record<string, ActionDefinition> = {
  'act-school-read': {
    id: 'act-school-read',
    category: 'school',
    chapter: 'The New City Vandara',
    cost: 5,
    costType: 'energy',
    yieldType: 'study_xp',
    rewards: { study_xp: 1 },
    sfx: 'craft',
    particleType: 'knowledge',
  },
  'act-school-numbers': {
    id: 'act-school-numbers',
    category: 'school',
    chapter: 'The New City Vandara',
    cost: 5,
    costType: 'energy',
    yieldType: 'study_xp',
    rewards: { study_xp: 1 },
    sfx: 'craft',
    particleType: 'knowledge',
  },
  'act-school-history': {
    id: 'act-school-history',
    category: 'school',
    chapter: 'The New City Vandara',
    cost: 10,
    costType: 'energy',
    requirements: { 'npcProgress.teacher': { op: '>=', val: 2 } },
    yieldType: 'study_xp',
    rewards: { study_xp: 3 },
    sfx: 'dialogue',
    particleType: 'knowledge',
  },
  'act-school-herbs': {
    id: 'act-school-herbs',
    category: 'school',
    chapter: 'The New City Vandara',
    cost: 5,
    costType: 'energy',
    requirements: { 'npcProgress.flowerGirl': { op: '>=', val: 3 } },
    rewards: { study_xp: 2, herbs: 1 },
    sfx: 'gather',
    particleType: 'knowledge',
  },
  'act-school-runes': {
    id: 'act-school-runes',
    category: 'school',
    chapter: 'The New City Vandara',
    cost: 10,
    costType: 'magic',
    requirements: { 'npcProgress.aris': { op: '>=', val: 2 } },
    rewards: { study_xp: 3, rune_fragment: 1 },
    sfx: 'magic',
    particleType: 'knowledge',
  },
};
